CREATE TYPE STATUS_TYPE AS ENUM('IN_PROGRESS', 'EXPIRED');

CREATE TABLE IF NOT EXISTS events(
	id CHAR(36) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(100) NOT NULL,
	segment VARCHAR(50) NOT NULL,
	local VARCHAR(255) NOT NULL,
	capacity INTEGER NOT NULL,
	occurs_at TIMESTAMP NOT NULL,
	status STATUS_TYPE NOT NULL,
	
	user_id CHAR(36) NOT NULL,
	CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);